"""Protocol describing the runtime surface CLI handlers depend on."""
from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from pathlib import Path

    from ai_agents_metrics.cost_audit import CostAuditReport
    from ai_agents_metrics.history.audit import AuditReport
    from ai_agents_metrics.history.classify import ClassifySummary
    from ai_agents_metrics.history.compare import (
        HistoryCompareReport,
        HistorySignals,
    )
    from ai_agents_metrics.history.derive import DeriveSummary
    from ai_agents_metrics.history.ingest import IngestSummary
    from ai_agents_metrics.history.normalize import NormalizeSummary
    from ai_agents_metrics.history.summary import WarehouseSummary
    from ai_agents_metrics.retro_timeline import RetroTimelineReport


# CommandRuntime aggregates the entire runtime surface that handle_* command
# functions depend on. 40 methods reflect the breadth of operations the CLI
# dispatches, not an architectural issue. Splitting would fragment the single
# type hint each handler uses, without reducing coupling.
class CommandRuntime(Protocol):  # pylint: disable=too-many-public-methods
    def ingest_codex_history(self, source_root: Path, warehouse_path: Path, source: str = ...) -> Any: ...
    def normalize_codex_history(self, warehouse_path: Path) -> Any: ...
    def classify_codex_history(self, warehouse_path: Path) -> Any: ...
    def derive_codex_history(self, warehouse_path: Path) -> Any: ...
    def verify_public_boundary(self, *, repo_root: Path, rules_path: Path) -> Any: ...
    def audit_cost_coverage(
        self,
        data: dict[str, Any],
        *,
        pricing_path: Path,
        codex_state_path: Path,
        codex_logs_path: Path,
        codex_thread_id: str | None,
        cwd: Path,
        claude_root: Path = ...,
    ) -> CostAuditReport: ...
    def load_metrics(self, path: Path) -> dict[str, Any]: ...
    def recompute_summary(self, data: dict[str, Any]) -> None: ...
    def load_warehouse_summary(self, warehouse_path: Path, project_cwd: Path) -> WarehouseSummary: ...
    def render_warehouse_summary(self, summary: WarehouseSummary) -> str: ...
    def render_warehouse_summary_json(self, summary: WarehouseSummary) -> str: ...
    def read_history_signals(self, warehouse_path: Path, project_cwd: Path, data: dict[str, Any]) -> HistorySignals | None: ...
    def audit_history(self, data: dict[str, Any]) -> AuditReport: ...
    def render_audit_report(self, report: AuditReport) -> str: ...
    def render_audit_report_json(self, report: AuditReport) -> str: ...
    def compare_metrics_to_history(
        self,
        data: dict[str, Any],
        *,
        warehouse_path: Path,
        cwd: Path,
        metrics_path: Path,
    ) -> HistoryCompareReport: ...
    def render_history_compare_report(self, report: HistoryCompareReport) -> str: ...
    def render_history_compare_report_json(self, report: HistoryCompareReport) -> str: ...
    def metrics_mutation_lock(self, path: Path) -> Any: ...
    def render_ingest_summary_json(self, summary: IngestSummary) -> str: ...
    def render_normalize_summary_json(self, summary: NormalizeSummary) -> str: ...
    def render_classify_summary_json(self, summary: ClassifySummary) -> str: ...
    def render_derive_summary_json(self, summary: DeriveSummary) -> str: ...
    def derive_retro_timeline(
        self,
        data: dict[str, Any],
        *,
        warehouse_path: Path,
        cwd: Path,
        metrics_path: Path,
        window_size: int,
    ) -> RetroTimelineReport: ...
    def render_retro_timeline_report(self, report: RetroTimelineReport) -> str: ...
    def render_retro_timeline_report_json(self, report: RetroTimelineReport) -> str: ...
    def render_cost_audit_report_json(self, report: CostAuditReport) -> str: ...
    def load_effective_pricing(self, *, cwd: Path, pricing_path: Path | None = None) -> dict[str, dict[str, float | None]]: ...
    def resolve_effective_pricing_path(self, *, cwd: Path, pricing_path: Path | None = None) -> Path: ...
    def resolve_pricing_path(self, cwd: Path) -> Path: ...
