"""Protocol describing the runtime surface CLI handlers depend on."""
from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from pathlib import Path

    from ai_agents_metrics.history.classify import ClassifySummary
    from ai_agents_metrics.history.derive import DeriveSummary
    from ai_agents_metrics.history.ingest import IngestSummary
    from ai_agents_metrics.history.normalize import NormalizeSummary
    from ai_agents_metrics.history.summary import WarehouseSummary


# CommandRuntime aggregates the entire runtime surface that handle_* command
# functions depend on. 40 methods reflect the breadth of operations the CLI
# dispatches, not an architectural issue. Splitting would fragment the single
# type hint each handler uses, without reducing coupling.
class CommandRuntime(Protocol):  # pylint: disable=too-many-public-methods
    def ingest_codex_history(self, source_root: Path, warehouse_path: Path, source: str = ...) -> Any: ...
    def normalize_codex_history(self, warehouse_path: Path) -> Any: ...
    def classify_codex_history(self, warehouse_path: Path) -> Any: ...
    def derive_codex_history(self, warehouse_path: Path) -> Any: ...
    def verify_public_boundary(self, *, repo_root: Path, rules_path: Path) -> Any: ...
    def load_warehouse_summary(self, warehouse_path: Path, project_cwd: Path) -> WarehouseSummary: ...
    def render_warehouse_summary(self, summary: WarehouseSummary) -> str: ...
    def render_warehouse_summary_json(self, summary: WarehouseSummary) -> str: ...
    def render_ingest_summary_json(self, summary: IngestSummary) -> str: ...
    def render_normalize_summary_json(self, summary: NormalizeSummary) -> str: ...
    def render_classify_summary_json(self, summary: ClassifySummary) -> str: ...
    def render_derive_summary_json(self, summary: DeriveSummary) -> str: ...
    def metrics_mutation_lock(self, path: Path) -> Any: ...
    def load_effective_pricing(self, *, cwd: Path, pricing_path: Path | None = None) -> dict[str, dict[str, float | None]]: ...
    def resolve_effective_pricing_path(self, *, cwd: Path, pricing_path: Path | None = None) -> Path: ...
    def resolve_pricing_path(self, cwd: Path) -> Path: ...
